#https://github.com/terrakok/kmp-awesome

[versions]
accompanistPager = "0.28.0"
accompanistSwiperefresh = "0.30.1"
activityKtx = "1.8.0"
android-compileSdk = "34"
android-minSdk = "26"
android-targetSdk = "34"
hilt = "2.47"

appcompat = "1.6.1"
cartoon = "2023.04.11"
collectionKtx = "1.3.0"
constraintlayout = "2.1.4"
constraintlayoutCompose = "1.1.0-alpha13"
cubic = "2023.04.11"
dynamicanimationKtx = "1.0.0-alpha03"
kotlin = "1.9.10"
android-gradle-plugin = "8.1.2"
ksp = "1.9.10-1.0.13"
lifecycle = "2.6.2"
lottie = "3.4.0"
material = "1.10.0"
navigationFragmentKtx = "2.7.4"
navigationUiKtx = "2.7.4"
paging = "3.2.1"
paletteKtx = "1.0.0"
spotless = "6.20.0"
detekt = "1.23.1"
kode-detekt-rules-compose = "1.3.0"
twitter-compose-rules = "0.0.26"
desugar-jdk-libs = "2.0.3"
recyclerview = "1.3.1"
swiperefreshlayout = "1.1.0"

androidx-compose-bom = "2023.10.00"
koin-bom = "3.5.1"
androidx-compose-compiler = "1.5.3"
androidx-benchmark = "1.1.1"
androidx-profileinstaller = "1.3.1"
androidx-core = "1.12.0"
androidx-core-splashscreen = "1.0.1"
androidx-activity = "1.8.0"
androidx-annotation = "1.7.0"
androidx-navigation = "2.7.4"
androidx-room = "2.5.2"
androidx-datastore = "1.0.0"
androidx-hilt = "1.0.0"
androidx-test-ext = "1.1.5"
androidx-test-espresso = "3.5.1"
androidx-test-uiautomator = "2.2.0"
junit = "4.13.2"
mockk = "1.13.5"

kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.5.1"
kotlinx-datetime = "0.4.0"

dagger = "2.47"
okhttp = "4.11.0"
retrofit = "2.9.0"
retrofit-kotlinx-serialization-converter = "1.0.0"

javax-inject = "1"

accompanist = "0.30.1"
coil = "2.4.0"
ktor = "2.3.4"
viewDsl = "2023.04.05"
adapter = "2023.10.13"
webkit = "1.8.0"
workRuntimeKtx = "2.8.1"
protobuf = "3.24.0"
protobufPlugin = "0.9.4"

[libraries]
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
sparkj-cartoon = { module = "osp.sparkj.ui:cartoon", version.ref = "cartoon" }
sparkj-cubic = { module = "osp.sparkj.ui:cubic", version.ref = "cubic" }
sparkj-view-dsl = { module = "osp.sparkj.ui:view-dsl", version.ref = "viewDsl" }
sparkj-adapter = { module = "osp.sparkj.ui:adapter", version.ref = "adapter" }

androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "collectionKtx" }
androidx-dynamicanimation-ktx = { module = "androidx.dynamicanimation:dynamicanimation-ktx", version.ref = "dynamicanimationKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-activity-compose = { module = "androidx.activity:activity-compose" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }

androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }

androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }

androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }

androidx-room-common = { module = "androidx.room:room-common", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-reactivestreams-ktx = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistSwiperefresh" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanistSwiperefresh" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanistSwiperefresh" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistSwiperefresh" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanistSwiperefresh" }

google-material = { module = "com.google.android.material:material", version.ref = "material" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

#https://insert-koin.io/docs/setup/koin/
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-compat = { module = "io.insert-koin:koin-android-compat" }
koin-android-test = { module = "io.insert-koin:koin-android-test" }
koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }
test-junit = { module = "junit:junit", version.ref = "junit" }
test-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

dagger-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlinx-serialization-converter" }

javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kode-detekt-rules-compose = { module = "ru.kode:detekt-rules-compose", version.ref = "kode-detekt-rules-compose" }
twitter-compose-rules-detekt = { module = "com.twitter.compose.rules:detekt", version.ref = "twitter-compose-rules" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

# Dependencies of the included build-logic.
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }


[bundles]
compose = [
    "androidx-compose-ui",
    "androidx-compose-material",
    "androidx-compose-material3",
    #    Optional - Add window size utils
    "androidx-compose-material3-window-size",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-activity-compose",
    #     Optional - Integration with activities
    "androidx-compose-activity",
    "androidx-compose-hilt-navigation",
    "androidx-compose-constraintlayout",
    "androidx-compose-foundation",
    "lifecycle-runtime-compose",
    "lifecycle-viewmodel-compose",
    "androidx-compose-ui-util",
    #         Optional - Included automatically by material, only add when you need
    #     the icons but not the material library (e.g. when using Material3 or a
    #     custom design system based on Foundation)
    "androidx-compose-material-icons-core",
    #    Optional - Add full set of material icons
    "androidx-compose-material-icons-extended",
    #     Optional - Integration with ViewModels
    #     Optional - Integration with LiveData
    "androidx-compose-runtime-livedata",
    "coil-compose",
    "androidx-paging-compose",
]
androidx-room = ["androidx-room-runtime", "androidx-room-ktx", "androidx-room-paging"]
#https://developer.android.google.cn/studio/profile/benchmark?hl=zh-cn
androidx-benchmark = [
    "androidx-test-ext-junit",
    "androidx-test-espresso-core",
    "androidx-test-uiautomator",
    "androidx-benchmark-macro-junit4"
]
retrofit = ["okhttp", "retrofit", "retrofit-kotlinx-serialization-converter"]
sparkj = ["sparkj-view-dsl", "sparkj-cubic", "sparkj-cartoon"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-test = { id = "com.android.test", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }